paths:
  input_dir: "../../data/in/"  # We will create this in the notebook
  output_dir: "../../data/out/distilled/"

teacher:
  device: "cuda"
  box_threshold: 0.35
  text_threshold: 0.25
  ontology_config:
    objects:
      person: person
      white coffee mug: cup
      plastic water bottle: bottle
      laptop computer: laptop
      rolling office chair: chair
